// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKqGywYwl2cxqvK8cSum7aHDyiG3MpnwE',
    appId: '1:795881171743:web:10b448fcb2031797f35e2a',
    messagingSenderId: '795881171743',
    projectId: 'iub-social-media-app',
    authDomain: 'iub-social-media-app.firebaseapp.com',
    storageBucket: 'iub-social-media-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHr7Vq3BDXdiQ6Owm9H3cLednQMq3qHTk',
    appId: '1:795881171743:android:4b443635035c20a6f35e2a',
    messagingSenderId: '795881171743',
    projectId: 'iub-social-media-app',
    storageBucket: 'iub-social-media-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8oFD64JK7PBNfvJY_DY-JD0z018ojtoo',
    appId: '1:795881171743:ios:105a5475dc176890f35e2a',
    messagingSenderId: '795881171743',
    projectId: 'iub-social-media-app',
    storageBucket: 'iub-social-media-app.firebasestorage.app',
    iosBundleId: 'com.example.iubSocial',
  );
}
